version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
      day: sunday

  - package-ecosystem: "npm"
    directory: "/tunnel-server"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
      day: sunday
  
