name: Publish to NPM
on:
  push:
    branches: 
    - master

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - uses: actions/checkout@v3

    - run: yarn

    - run: npm install -g @jsdevtools/npm-publish

    - name: npm publish
      run: |
        set -eou pipefail
        set -x

        for packageDir in docker-proxy cli; do
          npm-publish --token ${{ secrets.NPM_TOKEN }} --access public packages/${packageDir}/package.json
        done
