name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git branch or tree-like to publish from
        default: main
      bump:
        description: major, minor, patch, from-package
        default: patch

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: yarn

    - run: yarn

    - name: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        set -eou pipefail
        set -x

        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          lerna_args=${{ inputs.bump }}
        else
          lerna_args=-c
        fi

        yarn lerna publish --no-private -y --loglevel debug ${lerna_args}
